<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="4" ignored="3" total="11" passed="3">
  <reporter-output>
    <line>
      <![CDATA[Screenshot]]>
    </line>
    <line>
      <![CDATA[schreenshot]]>
    </line>
    <line>
      <![CDATA[case failed]]>
    </line>
    <line>
      <![CDATA[Screenshot]]>
    </line>
    <line>
      <![CDATA[Screenshot]]>
    </line>
    <line>
      <![CDATA[testing passed]]>
    </line>
    <line>
      <![CDATA[Screenshot]]>
    </line>
  </reporter-output>
  <suite name="MySecondSuit" duration-ms="669" started-at="2018-06-03T11:09:43Z" finished-at="2018-06-03T11:09:44Z">
    <groups>
    </groups>
    <test name="Select" duration-ms="31" started-at="2018-06-03T11:09:43Z" finished-at="2018-06-03T11:09:43Z">
      <class name="Config.SelectBrowser">
        <test-method status="FAIL" signature="selectBrowser()[pri:0, instance:Config.SelectBrowser@1a0cee9]" name="selectBrowser" duration-ms="0" started-at="2018-06-03T16:39:43Z" data-provider="getnumericno" finished-at="2018-06-03T16:39:43Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[Data Provider public int Config.SelectBrowser.getValue() must return either Object[][] or Object[] or Iterator<Object[]> or Iterator<Object>, not int]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: Data Provider public int Config.SelectBrowser.getValue() must return either Object[][] or Object[] or Iterator<Object[]> or Iterator<Object>, not intat org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:156)at org.testng.internal.Parameters.handleParameters(Parameters.java:706)at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:914)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1183)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectBrowser -->
      </class> <!-- Config.SelectBrowser -->
    </test> <!-- Select -->
    <test name="Save" duration-ms="77" started-at="2018-06-03T11:09:44Z" finished-at="2018-06-03T11:09:44Z">
      <class name="Config.Save">
        <test-method status="PASS" signature="test()[pri:0, instance:Config.Save@72e3f]" name="test" duration-ms="6" started-at="2018-06-03T16:39:44Z" finished-at="2018-06-03T16:39:44Z">
          <reporter-output>
            <line>
              <![CDATA[testing passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="testfailure()[pri:0, instance:Config.Save@72e3f]" name="testfailure" duration-ms="2" started-at="2018-06-03T16:39:44Z" finished-at="2018-06-03T16:39:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Google.com] but found [Yahoo.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Google.com] but found [Yahoo.com]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at Config.Save.testfailure(Save.java:22)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1183)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Screenshot]]>
            </line>
          </reporter-output>
        </test-method> <!-- testfailure -->
      </class> <!-- Config.Save -->
    </test> <!-- Save -->
  </suite> <!-- MySecondSuit -->
  <suite name="MultipleSuite" duration-ms="0" started-at="2018-06-03T11:09:47Z" finished-at="2018-06-03T11:09:47Z">
    <groups>
    </groups>
  </suite> <!-- MultipleSuite -->
  <suite name="MyFirstSuit" duration-ms="1767" started-at="2018-06-03T11:09:41Z" finished-at="2018-06-03T11:09:43Z">
    <groups>
      <group name="bvt">
        <method signature="HomePage.login()[pri:2, instance:Pages.HomePage@646db9]" name="login" class="Pages.HomePage"/>
        <method signature="Page2.testSkipCondition()[pri:1, instance:Pages.Page2@5185bd]" name="testSkipCondition" class="Pages.Page2"/>
        <method signature="Page2.validateTitleTest()[pri:2, instance:Pages.Page2@5185bd]" name="validateTitleTest" class="Pages.Page2"/>
      </group> <!-- bvt -->
      <group name="regression">
        <method signature="HomePage.login()[pri:2, instance:Pages.HomePage@646db9]" name="login" class="Pages.HomePage"/>
      </group> <!-- regression -->
    </groups>
    <test name="HomeBasic" duration-ms="368" started-at="2018-06-03T11:09:41Z" finished-at="2018-06-03T11:09:42Z">
      <class name="Pages.HomePage">
        <test-method status="PASS" signature="createDbCon()[pri:0, instance:Pages.HomePage@646db9]" name="createDbCon" is-config="true" duration-ms="132" started-at="2018-06-03T16:39:41Z" finished-at="2018-06-03T16:39:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDbCon -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:Pages.HomePage@646db9]" name="launchBrowser" is-config="true" duration-ms="16" started-at="2018-06-03T16:39:42Z" finished-at="2018-06-03T16:39:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="registration()[pri:1, instance:Pages.HomePage@646db9]" name="registration" duration-ms="17" started-at="2018-06-03T16:39:42Z" finished-at="2018-06-03T16:39:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registration -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:Pages.HomePage@646db9]" name="closeBrowser" is-config="true" duration-ms="1" started-at="2018-06-03T16:39:42Z" finished-at="2018-06-03T16:39:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:Pages.HomePage@646db9]" name="launchBrowser" is-config="true" duration-ms="1" started-at="2018-06-03T16:39:42Z" finished-at="2018-06-03T16:39:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="login()[pri:2, instance:Pages.HomePage@646db9]" name="login" duration-ms="6" started-at="2018-06-03T16:39:42Z" finished-at="2018-06-03T16:39:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:Pages.HomePage@646db9]" name="closeBrowser" is-config="true" duration-ms="1" started-at="2018-06-03T16:39:42Z" finished-at="2018-06-03T16:39:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="terminateDbCon()[pri:0, instance:Pages.HomePage@646db9]" name="terminateDbCon" is-config="true" duration-ms="1" started-at="2018-06-03T16:39:42Z" finished-at="2018-06-03T16:39:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateDbCon -->
      </class> <!-- Pages.HomePage -->
    </test> <!-- HomeBasic -->
    <test name="Assert" duration-ms="192" started-at="2018-06-03T11:09:43Z" finished-at="2018-06-03T11:09:43Z">
      <class name="Pages.Page2">
        <test-method status="SKIP" signature="testSkipCondition()[pri:1, instance:Pages.Page2@5185bd]" name="testSkipCondition" duration-ms="4" started-at="2018-06-03T16:39:43Z" finished-at="2018-06-03T16:39:43Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Condition not met]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Condition not metat Pages.Page2.testSkipCondition(Page2.java:32)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1183)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSkipCondition -->
        <test-method status="FAIL" signature="zest()[pri:1, instance:Pages.Page2@5185bd]" name="zest" duration-ms="23" started-at="2018-06-03T16:39:43Z" finished-at="2018-06-03T16:39:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[FORCEFULLY FAILED]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: FORCEFULLY FAILEDat org.testng.Assert.fail(Assert.java:96)at Pages.Page2.zest(Page2.java:27)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1183)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Screenshot]]>
            </line>
          </reporter-output>
        </test-method> <!-- zest -->
        <test-method status="FAIL" signature="validateTitleTest()[pri:2, instance:Pages.Page2@5185bd]" name="validateTitleTest" duration-ms="85" started-at="2018-06-03T16:39:43Z" finished-at="2018-06-03T16:39:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [google.com] but found [gmail.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [google.com] but found [gmail.com]at org.testng.Assert.fail(Assert.java:96)at Pages.Page2.validateTitleTest(Page2.java:20)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1183)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[schreenshot]]>
            </line>
            <line>
              <![CDATA[case failed]]>
            </line>
            <line>
              <![CDATA[Screenshot]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateTitleTest -->
      </class> <!-- Pages.Page2 -->
    </test> <!-- Assert -->
    <test name="TestDependancy" duration-ms="2" started-at="2018-06-03T11:09:43Z" finished-at="2018-06-03T11:09:43Z">
    </test> <!-- TestDependancy -->
  </suite> <!-- MyFirstSuit -->
</testng-results>
